const KEY='saldo.transactions.v1', SETTINGS='saldo.settings.v1';
let tx=read(KEY,[]), settings=read(SETTINGS,{startingBalance:0,incomeMode:'monthly',incomeAmount:0,payday:1,budget:0});
const cats=['อาหาร','เดินทาง','บ้านและบิล','ช้อปปิ้ง','สุขภาพ','บันเทิง','ออมและลงทุน','อื่นๆ'];
const money=n=>'฿'+Number(n||0).toLocaleString('th-TH',{maximumFractionDigits:2});
function read(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}function save(){localStorage.setItem(KEY,JSON.stringify(tx));localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function localDay(d=new Date()){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function icon(){return '<svg viewBox="0 0 24 24"><path d="M5 12h14M12 5v14"/></svg>'}function esc(s){const e=document.createElement('i');e.textContent=s;return e.innerHTML}
function isMonth(t){const d=new Date(t),n=new Date();return d.getMonth()==n.getMonth()&&d.getFullYear()==n.getFullYear()}
function totals(){const m=tx.filter(x=>isMonth(x.date));return{balance:Number(settings.startingBalance||0)+tx.reduce((s,x)=>s+(x.type==='income'?x.amount:-x.amount),0),income:m.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),expense:m.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0)}}
function classify(s){let t=s.toLowerCase();if(/เงินเดือน|โบนัส|รายได้|รับเงิน|ขายของ|ได้เงิน/.test(t))return'รายได้';if(/ข้าว|กาแฟ|ชา|อาหาร|กิน|ชาบู|ก๋วยเตี๋ยว|พิซซ่า|น้ำ/.test(t))return'อาหาร';if(/grab|แท็กซี่|รถ|bts|mrt|น้ำมัน|ทางด่วน/.test(t))return'เดินทาง';if(/ค่าไฟ|ค่าน้ำ|เน็ต|โทรศัพท์|เช่า|บ้าน/.test(t))return'บ้านและบิล';if(/ยา|หมอ|คลินิก|ฟิตเนส/.test(t))return'สุขภาพ';if(/netflix|เกม|หนัง|spotify/.test(t))return'บันเทิง';if(/หุ้น|กองทุน|ออม|ฝาก/.test(t))return'ออมและลงทุน';if(/shopee|lazada|เสื้อ|รองเท้า|ซื้อ/.test(t))return'ช้อปปิ้ง';return'อื่นๆ'}
function parseDate(s){const n=new Date();if(/เมื่อวาน/.test(s))n.setDate(n.getDate()-1);else if(/พรุ่งนี้/.test(s))n.setDate(n.getDate()+1);const d=s.match(/(\d{1,2})\s*[\/-]\s*(\d{1,2})(?:\s*[\/-]\s*(\d{2,4}))?/);if(d){n.setMonth(+d[2]-1,+d[1]);if(d[3])n.setFullYear(+d[3]<100?+d[3]+2500:+d[3]>2400?+d[3]-543:+d[3])}return localDay(n)}
function parse(raw){const lines=raw.split(/\n|(?<=\d)\s*(?:,|และ)\s*(?=[^\d])/).filter(Boolean);return lines.map(line=>{let numbers=line.match(/\b\d{1,3}(?:,\d{3})*(?:\.\d+)?\b/g)||[];let amount=Number((numbers.at(-1)||'').replaceAll(',',''));let cat=classify(line),type=cat==='รายได้'?'income':'expense';let name=line.replace(/\b\d{1,3}(?:,\d{3})*(?:\.\d+)?\b/g,'').replace(/เมื่อวาน|วันนี้|พรุ่งนี้|ตอนเช้า|เมื่อเช้า|สามทุ่ม|จ่าย(?:เงินสด|บัตร|จากธนาคาร)?/g,'').trim()||'ไม่ระบุรายการ';return{ id:crypto.randomUUID?.()||String(Date.now()+Math.random()),name,amount,type,category:type==='income'?'รายได้':cat,date:parseDate(line),time:'',source:'เงินสด',confidence:amount?(/อื่นๆ/.test(cat)?'กลาง':'สูง'):'ต่ำ'} }).filter(x=>x.amount>0)}
function render(){const t=totals(),today=localDay();document.querySelector('#today-label').textContent=new Date().toLocaleDateString('th-TH',{weekday:'long',day:'numeric',month:'short'});document.querySelector('#balance').textContent=money(t.balance);document.querySelector('#income-summary').textContent='รับเดือนนี้ '+money(t.income);document.querySelector('#expense-summary').textContent='จ่ายเดือนนี้ '+money(t.expense);let te=tx.filter(x=>x.date===today&&x.type==='expense').reduce((s,x)=>s+x.amount,0),ti=tx.filter(x=>x.date===today&&x.type==='income').reduce((s,x)=>s+x.amount,0);$('#today-expense').textContent=money(te);$('#today-income').textContent=money(ti);$('#budget-caption').textContent=settings.budget?`${money(te)} จากงบ ${money(settings.budget)}`:'ยังไม่ได้ตั้งงบวันนี้';$('#days-caption').textContent=settings.incomeAmount?`รายได้ ${settings.incomeMode==='monthly'?'รายเดือน':'รายวัน'} ${money(settings.incomeAmount)}`:'ตั้งรายได้เพื่อคาดการณ์';chart();categories();transactions()}
function chart(){let days=[...Array(7)].map((_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);return localDay(d)}),vals=days.map(d=>tx.filter(x=>x.date===d&&x.type==='expense').reduce((s,x)=>s+x.amount,0)),max=Math.max(...vals,1),pts=vals.map((v,i)=>`${i*50+10},${94-v/max*65}`).join(' '),labels=days.map((d,i)=>`<text x="${i*50+10}" y="119" text-anchor="middle" class="chart-label">${new Date(d+'T12:00').toLocaleDateString('th-TH',{weekday:'short'})}</text>`).join('');$('#trend-chart').innerHTML=`<defs><linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#147d68" stop-opacity=".22"/><stop offset="1" stop-color="#147d68" stop-opacity="0"/></linearGradient></defs><path d="M10 29H310M10 61H310M10 94H310" class="chart-grid"/><path d="M${pts} L310,94 L10,94Z" class="chart-area"/><polyline points="${pts}" class="chart-line"/>${labels}`}
function categories(){let map={};tx.filter(x=>isMonth(x.date)&&x.type==='expense').forEach(x=>map[x.category]=(map[x.category]||0)+x.amount);let a=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,4),max=a[0]?.[1]||1;$('#categories').innerHTML=a.length?a.map(([k,v])=>`<div class="category-row"><div class="category-label"><b>${esc(k)}</b><span>${money(v)}</span></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join(''):'<div class="empty">เริ่มบันทึกรายการเพื่อดูภาพรวม</div>'}
function transactions(){let a=[...tx].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);$('#transactions').innerHTML=a.length?a.map(x=>`<button class="transaction" data-id="${x.id}"><span class="transaction-icon">${icon()}</span><span class="transaction-body"><b>${esc(x.name)}</b><span>${esc(x.category)} · ${new Date(x.date+'T12:00').toLocaleDateString('th-TH',{day:'numeric',month:'short'})}</span></span><span class="amount ${x.type}">${x.type==='income'?'+':'-'}${money(x.amount)}</span></button>`).join(''):'<div class="empty">ยังไม่มีรายการ ลองพิมพ์ “กาแฟ 55”</div>';document.querySelectorAll('.transaction').forEach(b=>b.onclick=()=>edit(b.dataset.id))}
function modal(html){$('#modal-root').innerHTML=`<div class="overlay"><section class="sheet">${html}</section></div>`;$('.overlay').onclick=e=>{if(e.target===e.currentTarget)close()}}function close(){$('#modal-root').innerHTML=''}function toast(s){let x=document.createElement('div');x.className='toast';x.textContent=s;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function analyze(){let raw=$('#entry-text').value.trim();if(!raw)return;let list=parse(raw);if(!list.length){answer(raw);return}modal(`<h2>ตรวจรายการก่อนบันทึก</h2><p>ผู้ช่วยแยกจากข้อความของคุณแล้ว แก้ไขได้ก่อนบันทึก</p><div class="result">${list.map((x,i)=>`<div class="result-row"><b>${esc(x.name)}</b><small>${x.type==='income'?'รายรับ':'รายจ่าย'} · ${x.category}</small><strong>${money(x.amount)}</strong></div>`).join('')}</div><div class="actions"><button class="secondary" id="cancel">ยกเลิก</button><button class="primary" id="save-items">บันทึก ${list.length} รายการ</button></div>`);$('#cancel').onclick=close;$('#save-items').onclick=()=>{tx.push(...list);save();close();$('#entry-text').value='';render();toast('บันทึกรายการแล้ว')}}
function answer(q){let t=totals(), day=new Date().getDate(), remain=Math.max(0,new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate()-day);let message=/พอ|เหลือ|สิ้นเดือน/.test(q)?`ตอนนี้เหลือ ${money(t.balance)} ถ้าแบ่งใช้ถึงสิ้นเดือนอีก ${remain} วัน จะใช้ได้เฉลี่ยวันละ ${money(t.balance/Math.max(1,remain))}`:/อาหาร|หมวด/.test(q)?`เดือนนี้คุณใช้ไป ${money(t.expense)} โดยดูรายละเอียดแต่ละหมวดได้จากการ์ดด้านบน`:`เดือนนี้รับเข้า ${money(t.income)} และใช้ไป ${money(t.expense)} ตอนนี้คงเหลือ ${money(t.balance)}`;modal(`<h2>คำตอบจากผู้ช่วย</h2><p>${esc(message)}</p><p class="hint">เวอร์ชันนี้ตอบจากยอดจริงในเครื่อง เมื่อเชื่อม Gemini จะรองรับคำถามภาษาธรรมชาติที่ลึกขึ้น</p><div class="actions"><button class="primary" id="ok">เข้าใจแล้ว</button></div>`);$('#ok').onclick=close}
function edit(id){let x=tx.find(a=>a.id===id);modal(`<h2>แก้ไขรายการ</h2><label>ชื่อรายการ</label><input id="e-name" value="${esc(x.name)}"><label>จำนวนเงิน</label><input id="e-amount" type="number" value="${x.amount}"><label>ประเภท</label><select id="e-type"><option value="expense" ${x.type==='expense'?'selected':''}>รายจ่าย</option><option value="income" ${x.type==='income'?'selected':''}>รายรับ</option></select><label>หมวดหมู่</label><select id="e-cat">${['รายได้',...cats].map(c=>`<option ${x.category===c?'selected':''}>${c}</option>`)}</select><label>วันที่</label><input id="e-date" type="date" value="${x.date}"><div class="actions"><button class="secondary danger" id="delete">ลบ</button><button class="primary" id="update">บันทึก</button></div>`);$('#delete').onclick=()=>{tx=tx.filter(a=>a.id!==id);save();close();render()};$('#update').onclick=()=>{x.name=$('#e-name').value.trim()||'ไม่ระบุรายการ';x.amount=Number($('#e-amount').value);x.type=$('#e-type').value;x.category=$('#e-cat').value;x.date=$('#e-date').value;save();close();render()}}
function settingsSheet(){modal(`<h2>ตั้งค่าและข้อมูล</h2><p>ข้อมูลอยู่บนเครื่องนี้จนกว่าจะเชื่อมระบบสำรองคลาวด์</p><label>ยอดเริ่มต้น</label><input id="s-balance" type="number" value="${settings.startingBalance}"><label>รายได้หลัก</label><select id="s-mode"><option value="monthly" ${settings.incomeMode==='monthly'?'selected':''}>รายเดือน</option><option value="daily" ${settings.incomeMode==='daily'?'selected':''}>รายวัน</option><option value="variable" ${settings.incomeMode==='variable'?'selected':''}>ไม่แน่นอน</option></select><label>ยอดรายได้โดยประมาณ</label><input id="s-income" type="number" value="${settings.incomeAmount}"><label>งบใช้จ่ายต่อวัน</label><input id="s-budget" type="number" value="${settings.budget}"><div class="actions"><button class="secondary" id="import">นำเข้า</button><button class="secondary" id="download">ส่งออก</button></div><div class="actions"><button class="secondary" id="close">ยกเลิก</button><button class="primary" id="s-save">บันทึก</button></div>`);$('#close').onclick=close;$('#s-save').onclick=()=>{settings={...settings,startingBalance:Number($('#s-balance').value)||0,incomeMode:$('#s-mode').value,incomeAmount:Number($('#s-income').value)||0,budget:Number($('#s-budget').value)||0};save();close();render()};$('#download').onclick=download;$('#import').onclick=()=>$('#import-file').click()}
function download(){let blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),settings,transactions:tx},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`saldo-backup-${localDay()}.json`;a.click();URL.revokeObjectURL(a.href);toast('ดาวน์โหลดไฟล์สำรองแล้ว')}
$('#import-file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let d=JSON.parse(await f.text());if(!Array.isArray(d.transactions))throw Error();if(!confirm(`นำเข้า ${d.transactions.length} รายการและแทนที่ข้อมูลปัจจุบัน?`))return;tx=d.transactions;settings={...settings,...d.settings};save();close();render();toast('นำเข้าข้อมูลสำเร็จ')}catch{toast('ไฟล์สำรองไม่ถูกต้อง')}finally{e.target.value=''}};
const $=s=>document.querySelector(s);$('#analyze-btn').onclick=analyze;$('#entry-text').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();analyze()}};$('#settings-btn').onclick=settingsSheet;$('#export-btn').onclick=download;$('#add-fab').onclick=()=>$('#entry-text').focus();$('#insights-btn').onclick=()=>{ $('#entry-text').focus();$('#entry-text').placeholder='ลองถาม “เดือนนี้ใช้มากไปไหม”'};$('#categories-btn').onclick=()=>toast('แสดง 4 หมวดสูงสุดของเดือนนี้');$('#period-btn').onclick=()=>toast('กราฟ 7 วันในเวอร์ชันแรก');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
